name: Convert Config Files and Push to Yokosuka

on:
  push:
    branches:
      - main

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Run conversion script
      run: |
        python convert.py

    - name: Pull latest changes from Yokosuka branch
      run: |
        git checkout -B Yokosuka
        git pull origin Yokosuka --rebase --strategy-option ours

    - name: Apply stashed files
      run: |
        git stash pop

    - name: Remove unnecessary files in Yokosuka branch
      run: |
        git rm -rf .github
        git rm -rf convert.py
        git rm -rf LICENSE

    - name: Commit and push changes to Yokosuka branch
      run: |
        git add yaml/*.yaml
        git add list/*.list
        git commit -m "auto-gen files"
        git push origin Yokosuka --force
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
