name: Convert Config Files and Push to Yokosuka

on:
  push:
    branches:
      - main

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Run conversion script
      run: |
        python convert.py
        
    - name: Commit and push changes to Yokosuka branch
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git checkout -B Yokosuka
        git add yaml/*.yaml
        git add list/*.list
        git commit -m "雪の冠雲の帯 いつもけだかき姿にて"
        git push origin Yokosuka
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
