name: Convert Config Files

on:
  push:
    branches:
      - main

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Run conversion script
      run: |
        python convert.py

    - name: Commit and push changes if any
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git add -f yaml/*.yaml
        git diff --cached --quiet || git commit -m "Auto-gen .yaml files .list"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
