name: Convert and Push List and YAML Files

on:
  push:
    branches:
      - main

jobs:
  convert_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main branch
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Run conversion script
      run: |
        python convert.py

    - name: Push to yaml-branch
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git checkout -B Yokosuka
        git add list/*.list
        git add yaml/*.yaml
        git commit -m "Auto-gen"
        git push --force origin Yokosuka
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
